name: 🍺 CI · Formula

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: Ref.
        required: false
        type: string

permissions: {}

jobs:
  formula:
    runs-on: macos-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: "🧑‍💻 Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: "🍺 Audit"
        shell: sh
        run: |
          set -eu
          for formula in Casks/*.rb Formula/*.rb; do
            test -f "${formula}" || continue
            case "${formula}" in
              Casks/*)
                brew style "${formula}"
                ;;
              Formula/*)
                brew style "${formula}"
                ;;
            esac
          done
